#!/usr/bin/env python3
"""build.py — regenerates library/INDEX.md and site/index.html from the library.

Site identity: brand v1 "Weft" (see charter/BRAND.md and ADR-003) — the genesis blueprint
structure kept, restyled from pre-brand blues to the loom palette, with the weft line as
its signature. Template changes follow the two-iteration ADR rule. Stdlib only.
"""
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOOPS = ROOT / "library" / "loops"


def parse_front_matter(text):
    parts = text.split("---", 2)
    meta = {}
    if len(parts) < 3:
        return meta, text
    for line in parts[1].strip().splitlines():
        if ":" not in line or line.strip().startswith("#"):
            continue
        key, _, raw = line.partition(":")
        key, raw = key.strip(), raw.split(" #")[0].strip()
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            meta[key] = [v.strip() for v in inner.split(",") if v.strip()] if inner else []
        else:
            meta[key] = raw
    return meta, parts[2]


def first_paragraph(body):
    lines, out, seen_h1 = body.splitlines(), [], False
    for line in lines:
        if line.startswith("# "):
            seen_h1 = True
            continue
        if seen_h1:
            if line.startswith("#"):
                break
            if line.strip():
                out.append(line.strip())
            elif out:
                break
    return " ".join(out)


def run_command(body):
    """Extract the .claude/commands/<slug>.md block from a '## Run it' section, if present.
    Returns the raw command text (for a one-click copy on the card), or "" if the loop has
    not been converted yet."""
    if "## Run it" not in body:
        return ""
    section = body.split("## Run it", 1)[1].split("\n## ", 1)[0]
    m = re.search(r"```(?:markdown)?\n(.*?)\n```", section, re.S)
    return m.group(1).strip() if m else ""


def collect():
    entries = []
    for path in sorted(LOOPS.rglob("LP-*.md")):
        meta, body = parse_front_matter(path.read_text())
        meta["purpose"] = first_paragraph(body)
        meta["command"] = run_command(body)
        meta["path"] = str(path.relative_to(ROOT))
        entries.append(meta)
    return entries


def build_index(entries, tax, state):
    cats = {c["id"]: c for c in tax["categories"]}
    name = state.get("name") or f"{state.get('codename', 'loopforge')} (pre-brand)"
    lines = [
        "<!-- GENERATED by tools/build.py — do not edit by hand -->",
        f"# {name} — Library Index",
        "",
        f"{len(entries)} loops · iteration {state.get('iteration', 0)} · phase {state.get('phase', '?')}",
        "",
    ]
    for cat_id, cat in cats.items():
        group = [e for e in entries if e.get("category") == cat_id]
        lines.append(f"## {cat['name']} — {cat['desc']}")
        if not group:
            lines.append("_empty — a gap the Scout should notice_")
        for e in group:
            tags = ", ".join(e.get("tags", []))
            lines.append(
                f"- **[{e['id']} · {e['title']}]({e['path'].replace('library/', '')})** "
                f"`{e.get('tier', '?')}` `{e.get('status', '?')}` — {e.get('purpose', '')[:140]} "
                f"_(tags: {tags})_"
            )
        lines.append("")
    (ROOT / "library" / "INDEX.md").write_text("\n".join(lines) + "\n")


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@@TITLE@@ — loop library</title>
<style>
  /* brand v1 — Weft (ADR-003). Loom palette: warp/cloth grounds, thread/selvage
     inks, weft-gold signature, teal flash. Names kept stable; hexes are the brand. */
  :root{
    --field:#0E1726; --panel:#16233A; --line:#5B7186; --ink:#C9D6E5;
    --dim:#7E93A8; --mark:#E8C468; --flash:#6FB2A8;
  }
  *{box-sizing:border-box; margin:0}
  body{
    font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace;
    background:
      repeating-linear-gradient(0deg, transparent 0 23px, rgba(201,214,229,.05) 23px 24px),
      repeating-linear-gradient(90deg, transparent 0 23px, rgba(201,214,229,.05) 23px 24px),
      var(--field);
    color:var(--ink); font-size:14px; line-height:1.55; padding:20px;
    min-height:100vh;
  }
  a{color:var(--flash)}
  .sheet{max-width:1040px; margin:0 auto; border:2px solid var(--line); position:relative; background:rgba(22,35,58,.6)}
  .reg{position:absolute; width:14px; height:14px; border:1px solid var(--line)}
  .reg.tl{top:-7px; left:-7px} .reg.tr{top:-7px; right:-7px}
  .reg.bl{bottom:-7px; left:-7px} .reg.br{bottom:-7px; right:-7px}
  /* title block — the signature */
  .titleblock{display:grid; grid-template-columns:2fr 1fr 1fr 1fr; border-bottom:2px solid var(--line)}
  .cell{border-right:1px solid var(--line); padding:10px 14px; min-width:0}
  .cell:last-child{border-right:none}
  .cell .k{font-size:10px; letter-spacing:.22em; color:var(--dim); text-transform:uppercase}
  .cell .v{font-size:20px; font-weight:700; letter-spacing:.06em; text-transform:uppercase; overflow-wrap:anywhere}
  .cell .v.small{font-size:14px; font-weight:400; text-transform:none; letter-spacing:0}
  .strap{padding:10px 14px; color:var(--dim); font-size:12px; letter-spacing:.08em}
  /* the signature — a single weft carried across the warp (charter/BRAND.md) */
  .weftline{padding:0 14px 10px; color:var(--mark); font-size:12px; letter-spacing:.02em;
    overflow:hidden; white-space:nowrap; border-bottom:1px solid var(--line)}
  /* toolbar */
  .tools{display:flex; flex-wrap:wrap; gap:10px; padding:14px; border-bottom:1px solid var(--line); align-items:center}
  .tools input{
    flex:1 1 240px; background:transparent; border:1px solid var(--line); color:var(--ink);
    font:inherit; padding:8px 10px;
  }
  .tools input::placeholder{color:var(--dim)}
  .chip{
    background:transparent; border:1px dashed var(--dim); color:var(--dim); font:inherit;
    font-size:12px; padding:6px 10px; cursor:pointer; letter-spacing:.06em;
  }
  .chip[aria-pressed="true"]{border:1px solid var(--ink); color:var(--ink)}
  .chip:focus-visible, .tools input:focus-visible, a:focus-visible{outline:2px solid var(--mark); outline-offset:2px}
  /* cards */
  .grid{display:grid; grid-template-columns:repeat(auto-fill,minmax(300px,1fr)); gap:14px; padding:14px}
  .card{border:1px solid var(--line); padding:12px 14px; background:var(--panel); display:flex; flex-direction:column; gap:8px}
  .card .top{display:flex; justify-content:space-between; gap:8px; align-items:baseline}
  .card .id{color:var(--dim); font-size:12px; letter-spacing:.14em}
  .stamp{font-size:10px; letter-spacing:.16em; text-transform:uppercase; padding:2px 7px; border:1px solid var(--line); white-space:nowrap}
  .stamp.draft{border-style:dashed; color:var(--mark); border-color:var(--mark)}
  .stamp.reviewed{color:var(--ink)}
  .stamp.canonical{background:var(--ink); color:var(--field); border-color:var(--ink); font-weight:700}
  .stamp.deprecated{color:var(--dim); text-decoration:line-through}
  .card h2{font-size:16px; letter-spacing:.04em; text-transform:uppercase}
  .card p{color:var(--dim); font-size:13px}
  .meta{display:flex; flex-wrap:wrap; gap:6px; margin-top:auto}
  .tag{font-size:11px; color:var(--dim); border-bottom:1px dotted var(--dim)}
  .tier{font-size:11px; color:var(--ink); border:1px solid var(--dim); padding:1px 6px}
  .stopline{font-size:11px; color:var(--dim)}
  .stopline b{color:var(--ink); font-weight:400; letter-spacing:.1em}
  /* one-click copy of the loop's slash-command (## Run it) */
  .copybtn{align-self:flex-start; margin-top:2px; background:transparent; color:var(--mark);
    border:1px solid var(--mark); font:inherit; font-size:11px; letter-spacing:.08em;
    padding:4px 9px; cursor:pointer}
  .copybtn:hover{background:var(--mark); color:var(--field)}
  .copybtn:focus-visible{outline:2px solid var(--mark); outline-offset:2px}
  .empty{padding:40px 14px; color:var(--dim); text-align:center; display:none}
  footer{padding:12px 14px; border-top:1px solid var(--line); color:var(--dim); font-size:11px; letter-spacing:.06em; display:flex; flex-wrap:wrap; gap:6px 18px}
  @media (max-width:640px){ .titleblock{grid-template-columns:1fr 1fr} .cell:nth-child(2){border-right:none} }
  @media (prefers-reduced-motion:no-preference){ .card{transition:border-color .15s} .card:hover{border-color:var(--ink)} }
</style>
</head>
<body>
<div class="sheet">
  <span class="reg tl"></span><span class="reg tr"></span><span class="reg bl"></span><span class="reg br"></span>
  <header class="titleblock" aria-label="drawing title block">
    <div class="cell"><div class="k">Project</div><div class="v">@@TITLE@@</div></div>
    <div class="cell"><div class="k">Iteration</div><div class="v">@@ITER@@</div></div>
    <div class="cell"><div class="k">Phase</div><div class="v small">@@PHASE@@</div></div>
    <div class="cell"><div class="k">Loops on file</div><div class="v">@@COUNT@@</div></div>
  </header>
  <p class="strap">@@STRAP@@</p>
  <div class="weftline" aria-hidden="true">&gt;-------------------------------------------------------------&gt;</div>
  <div class="tools">
    <input id="q" type="search" placeholder="Search loops by name, tag, or purpose" aria-label="Search loops">
    @@CHIPS@@
  </div>
  <main class="grid" id="grid"></main>
  <p class="empty" id="empty">No loops match. Clear a filter — or check state/BACKLOG.md: maybe this loop hasn't been forged yet.</p>
  <footer>
    <span>Sheet 1 of 1 · scale 1:1 · drawn by the loop itself</span>
    <span>brand v1 · Weft — the weft line is the signature (charter/BRAND.md · ADR-003)</span>
    <span>generated @@STAMP@@ by tools/build.py</span>
  </footer>
</div>
<script>
const DATA = @@DATA@@;
const CATS = @@CATS@@;
const grid = document.getElementById('grid');
const empty = document.getElementById('empty');
const q = document.getElementById('q');
let activeCat = null;

function card(e){
  const el = document.createElement('article');
  el.className = 'card';
  el.innerHTML =
    '<div class="top"><span class="id">' + e.id + ' / ' + (CATS[e.category]||e.category) + '</span>' +
    '<span class="stamp ' + e.status + '">' + e.status + '</span></div>' +
    '<h2>' + e.title + '</h2>' +
    '<p>' + e.purpose + '</p>' +
    '<p class="stopline"><b>STOPS WHEN</b> ' + e.stop_when + '</p>' +
    '<div class="meta"><span class="tier">' + e.tier + '</span>' +
    e.tags.map(t => '<span class="tag">' + t + '</span>').join('') + '</div>';
  if (e.command){
    const b = document.createElement('button');
    b.type = 'button'; b.className = 'copybtn';
    b.textContent = 'Copy /command';
    b.title = 'Copy this loop as a Claude Code slash command — save to .claude/commands/, run with /loop';
    b.addEventListener('click', () => {
      navigator.clipboard.writeText(e.command).then(() => {
        b.textContent = 'Copied ✓';
        setTimeout(() => { b.textContent = 'Copy /command'; }, 1500);
      });
    });
    el.appendChild(b);
  }
  return el;
}
function render(){
  const needle = q.value.trim().toLowerCase();
  grid.textContent = '';
  let shown = 0;
  for (const e of DATA){
    if (activeCat && e.category !== activeCat) continue;
    const hay = (e.id + ' ' + e.title + ' ' + e.purpose + ' ' + e.tags.join(' ') + ' ' + e.tier).toLowerCase();
    if (needle && !hay.includes(needle)) continue;
    grid.appendChild(card(e)); shown++;
  }
  empty.style.display = shown ? 'none' : 'block';
}
q.addEventListener('input', render);
for (const chip of document.querySelectorAll('.chip')){
  chip.addEventListener('click', () => {
    const cat = chip.dataset.cat;
    activeCat = (activeCat === cat) ? null : cat;
    for (const c of document.querySelectorAll('.chip'))
      c.setAttribute('aria-pressed', String(c.dataset.cat === activeCat));
    render();
  });
}
render();
</script>
</body>
</html>
"""


def build_site(entries, tax, state):
    title = state.get("name") or "UNNAMED"
    strap = (
        "A self-running library of loop prompts for Claude Code — built, reviewed, "
        "filed, and branded by the loop that maintains it."
    )
    data = [
        {
            "id": e.get("id", "?"),
            "title": html.escape(e.get("title", "?")),
            "category": e.get("category", "?"),
            "tier": e.get("tier", "?"),
            "status": e.get("status", "draft"),
            "tags": [html.escape(t) for t in e.get("tags", [])],
            "purpose": html.escape(e.get("purpose", "")),
            "stop_when": html.escape(e.get("stop_when", "")),
            # raw (not HTML-escaped): written to the clipboard verbatim, never as innerHTML
            "command": e.get("command", ""),
            "path": e.get("path", ""),
        }
        for e in entries
    ]
    chips = "\n    ".join(
        f'<button class="chip" data-cat="{c["id"]}" aria-pressed="false">{html.escape(c["name"])}</button>'
        for c in tax["categories"]
    )
    cats = {c["id"]: c["name"] for c in tax["categories"]}
    page = (
        TEMPLATE
        .replace("@@TITLE@@", html.escape(title))
        .replace("@@ITER@@", str(state.get("iteration", 0)).zfill(3))
        .replace("@@PHASE@@", html.escape(str(state.get("phase", "?"))))
        .replace("@@COUNT@@", str(len(entries)).zfill(3))
        .replace("@@STRAP@@", strap)
        .replace("@@CHIPS@@", chips)
        .replace("@@DATA@@", json.dumps(data))
        .replace("@@CATS@@", json.dumps(cats))
        .replace("@@STAMP@@", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%MZ"))
    )
    (ROOT / "site" / "index.html").write_text(page)


def main():
    tax = json.loads((ROOT / "library" / "categories.json").read_text())
    state = json.loads((ROOT / "state" / "STATE.json").read_text())
    entries = collect()
    build_index(entries, tax, state)
    build_site(entries, tax, state)
    print(f"BUILD: OK — INDEX.md + site/index.html ({len(entries)} entries)")


if __name__ == "__main__":
    main()
